name: Activate Schedule
on: workflow_dispatch

jobs:
  activate:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "✅ Активация schedule..."
          mkdir -p .github
          date > .github/activated
